### ISSUE TITLE
Include authors in search criteria

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-core-functionality#14]
We should be able to search an author's name and get back posts by them.

**Comment by misfist** [comment]
I've added a plugin that improves the core WP search and adds configuration options within the dashboard (Settings > Relevanssi). Please have a look-see on staging to see it in action.

Note: there is a "pro" version of the plugin that enables you to weight different fields in order to return more relevant results.

**Comment by frnsys** [comment]
Looks good -- do you know if the pro version includes a way to prioritize author matches? I don't see it in the current settings. In any case, even if that's not available this works better, thanks!

**Comment by misfist** [comment]
Yes, the premium version enables you to weight based on taxonomy (or other criteria). 

Interestingly, it also lists the most common words

**Comment by misfist** [comment]
This is fulfilled by the relevanssi plugin that has been added.
