### ISSUE TITLE
Single pages for bundles

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-core-functionality#43]
Currently if I try to access a bundle at something like `/bundle/foo-bar`, I get a 404. If I try to access `/bundle` it redirects to `/bundle-theory` (I guess wordpress automatically searches for the closest article? Or is there an explicit redirect set-up somewhere? I wasn't able to find one).

**Comment by misfist** [comment]
This should work (it does for me locally). However, sometimes, you need to "fix" the permalinks, by going to Settings > Permalinks and hitting Save. 

Let me know if that fixes things.

**Comment by frnsys** [comment]
Ah yup that did it!

**Comment by misfist** [comment]
I little more info...

A page for a taxonomy term is considered an archive page in WordPress. Since we don't have a more specific template for it, the `archive.php` template is used. So, to customize the appearance, we can either create a specific archive template or add logic to archive.php, which pulls in a specific content if the taxonomy is "bundle".

`is_tax( 'bundle' )`

Here is a reference: https://developer.wordpress.org/themes/basics/template-hierarchy/#visual-overview
